name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: "Run Test with default python"
      run: echo "$(dirname $0) $(ls -lart ../)"
   #   run: "./auto/run-local-test"

    - name: "Run Test with python2"
      run: ls -lart
  #    run: "./auto/run-local-test-with-python2"
