name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: "./auto/run-local-test"
      name: "Run Test with default python"

    - uses: "./auto/run-local-test-with-python2"
      name: "Run Test with python2"
