name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/clean-agent-demo@master
    - name: "Run Test with default python"
      run: echo "$(dirname $0) $(ls -lart ../clean-agent-demo/)"
   #   run: "./auto/run-local-test"

    - name: "Run Test with python2"
      run: "../clean-agent-demo/auto/run-local-test-with-python2"
